name: event_creation
channels:
- pennmem
- conda-forge
dependencies:
- hdf5=1.8.17=1
- matplotlib
- nose=1.3.7=py27_1
- numpy=1.13
- pandas
- pip=9.0.1=py27_1
- pyqt=4.11.4=py27_4
- pytables=3.3.0=np113py27_0
- python=2.7.13=0
- python-dateutil=2.5.3=py27_0
- pyyaml=3.12=py27_0
- qt=4.8.7=4
- scipy=0.19
- swig=3.0.10=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xarray=0.8.2=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- xlrd=1.0.0
- sympy=1.1.0
- ptsa
- bptools
- h5py
- pyedflib=0.1
- nibabel=2
- mne
- scikit-image
- requests

