name: event_creation
channels:
    - free
    - pennmem
    - conda-forge
dependencies:
    - h5py
    - matplotlib
    - numpy<1.16
    - nose
    - pandas
    - pip>=10
    - pyqt=4.11
    - python=2.7.18
    - python-dateutil
    - pyyaml
    - qt=4.8
    - scikit-learn
    - scipy
    - tk=8.6.8
    - xarray
    - sympy
    - ptsa=2.0.4
    - pywavelets
    - scikit-image
    - requests
    - bptools
    - nibabel
    - pyedflib
    - mne<=0.17
    - pytables
    - bz2file
    - pip:
        - nolds
