name: event_creation
channels:
- free
- pennmem
- conda-forge
dependencies:
- h5py
- hdf5=1.8.17
- matplotlib
- mkl
- mkl-service
- numpy
- nose
- pandas
- pip
- pyqt=4.11
- python=2.7
- python-dateutil
- pyyaml=3.12
- qt=4.8
- scikit-learn
- scipy=1.2.1
- swig=3.0.10
- tk=8.6.8
- wheel=0.33
- xarray
- yaml=0.1.7
- zlib=1.2.11
- xlrd=1.0.0
- sympy
- ptsa
- pywavelets=0.5.1
- scikit-image
- requests
- pip:
  - bz2file
  - mne<=0.17
  - nibabel
  - pyedflib
  - tables
  - nolds

