name: event_creation
dependencies:
- hdf5=1.8.17=1
- matplotlib
- nose=1.3.7=py27_1
- numpy=1.11.3
- pandas=0.19.0=np111py27_0
- pip=9.0.1=py27_1
- pyqt=4.11.4=py27_4
- pytables=3.3.0=np111py27_0
- python=2.7.13=0
- python-dateutil=2.5.3=py27_0
- pyyaml=3.12=py27_0
- qt=4.8.7=4
- scipy=0.18.1
- swig=3.0.10=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xarray=0.8.2=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- scikit-image
- pip:
  - pyedflib==0.1.6
  - pywavelets==0.5.1
  - tables==3.3.0
  - nibabel==2.1.0
  - mne
