name: event_creation
channels:
  - free
  - pennmem
  - defaults
dependencies:
  - h5py
  - hdf5
  - matplotlib
  - numpy
  - numpy-base
  - pandas
  - pip
  - nose
  - python=2.7
  - python-dateutil
  - pyqt=4.11
  - qt=4.8
  - pyyaml=3.12
  - scipy=1.2.1
  - tk=8.6.8
  - wheel=0.33
  - yaml=0.1.7
  - zlib=1.2.11
  - sympy
  - scikit-image
  - requests
  - pip:
    - bz2file
    - mne
    - nibabel
    - ptsa
    - pyedflib
    - tables

