{% set setup_data = load_setup_py_data() %}

package:
  name: event_creation
  version: {{ setup_data['version'] }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - xlrd
    - matplotlib
    - pyyaml
    - sympy
    - h5py
    - pandas
    - ptsa
    - bptools

  test:
    imports:
      - event_creation
      - event_creation.submission
      - event_creation.neurorad



